2024-07-09 22:59:57.034506: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (bhc0003): /proc/driver/nvidia/version does not exist
Traceback (most recent call last):
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib64/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1880, in _create_c_op
    c_op = pywrap_tf_session.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling3d_1/MaxPool3D}} = MaxPool3D[T=DT_FLOAT, data_format="NDHWC", ksize=[1, 2, 2, 2, 1], padding="VALID", strides=[1, 2, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,1,64].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "model_cnn.py", line 106, in <module>
    main()
  File "model_cnn.py", line 99, in main
    length, accuracy, precision, recall, f1, mse, mae = process_and_evaluate_model(filename, test_size, input_shape, task_name)
  File "model_cnn.py", line 62, in process_and_evaluate_model
    model = build_cnn_model(input_shape)
  File "model_cnn.py", line 20, in build_cnn_model
    Dense(1, activation='sigmoid')
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib64/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 530, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib/python3.6/site-packages/keras/engine/sequential.py", line 134, in __init__
    self.add(layer)
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib64/python3.6/site-packages/tensorflow/python/training/tracking/base.py", line 530, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib/python3.6/site-packages/keras/engine/sequential.py", line 217, in add
    output_tensor = layer(self.outputs[0])
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 977, in __call__
    input_list)
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 1115, in _functional_construction_call
    inputs, input_masks, args, kwargs)
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 848, in _keras_tensor_symbolic_call
    return self._infer_output_signature(inputs, args, kwargs, input_masks)
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib/python3.6/site-packages/keras/engine/base_layer.py", line 888, in _infer_output_signature
    outputs = call_fn(inputs, *args, **kwargs)
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib/python3.6/site-packages/keras/layers/pooling.py", line 700, in call
    padding=self.padding.upper())
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib64/python3.6/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
    return target(*args, **kwargs)
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib64/python3.6/site-packages/tensorflow/python/ops/nn_ops.py", line 4935, in max_pool3d
    name=name)
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib64/python3.6/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 5456, in max_pool3d
    padding=padding, data_format=data_format, name=name)
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib64/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib64/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 601, in _create_op_internal
    compute_device)
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib64/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3569, in _create_op_internal
    op_def=op_def)
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib64/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2042, in __init__
    control_input_ops, op_def)
  File "/gpfs/fs1/home/qshi10/PycharmProjects/pythonProject/venv/lib64/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1883, in _create_c_op
    raise ValueError(str(e))
ValueError: Negative dimension size caused by subtracting 2 from 1 for '{{node max_pooling3d_1/MaxPool3D}} = MaxPool3D[T=DT_FLOAT, data_format="NDHWC", ksize=[1, 2, 2, 2, 1], padding="VALID", strides=[1, 2, 2, 2, 1]](Placeholder)' with input shapes: [?,1,1,1,64].
